// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: geo.sql

package db

import (
	"context"
)

const createAirport = `-- name: CreateAirport :one
INSERT INTO airports (city_id, iata_code, icao_code, lat, lon)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, city_id, iata_code, icao_code, lat, lon
`

type CreateAirportParams struct {
	CityID   int64
	IataCode *string
	IcaoCode *string
	Lat      *float64
	Lon      *float64
}

func (q *Queries) CreateAirport(ctx context.Context, arg CreateAirportParams) (Airport, error) {
	row := q.db.QueryRow(ctx, createAirport,
		arg.CityID,
		arg.IataCode,
		arg.IcaoCode,
		arg.Lat,
		arg.Lon,
	)
	var i Airport
	err := row.Scan(
		&i.ID,
		&i.CityID,
		&i.IataCode,
		&i.IcaoCode,
		&i.Lat,
		&i.Lon,
	)
	return i, err
}

const createCity = `-- name: CreateCity :one
INSERT INTO cities (country_id, name_ro, name_ru, name_en, is_capital, population, timezone)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, country_id, name_ro, name_ru, name_en, is_capital, population, timezone
`

type CreateCityParams struct {
	CountryID  int64
	NameRo     string
	NameRu     string
	NameEn     string
	IsCapital  bool
	Population *int64
	Timezone   *string
}

func (q *Queries) CreateCity(ctx context.Context, arg CreateCityParams) (City, error) {
	row := q.db.QueryRow(ctx, createCity,
		arg.CountryID,
		arg.NameRo,
		arg.NameRu,
		arg.NameEn,
		arg.IsCapital,
		arg.Population,
		arg.Timezone,
	)
	var i City
	err := row.Scan(
		&i.ID,
		&i.CountryID,
		&i.NameRo,
		&i.NameRu,
		&i.NameEn,
		&i.IsCapital,
		&i.Population,
		&i.Timezone,
	)
	return i, err
}

const createCountry = `-- name: CreateCountry :one
INSERT INTO countries (name_ro, name_ru, name_en, iso3, iso2)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name_ro, name_ru, name_en, iso3, iso2
`

type CreateCountryParams struct {
	NameRo string
	NameRu string
	NameEn string
	Iso3   string
	Iso2   string
}

func (q *Queries) CreateCountry(ctx context.Context, arg CreateCountryParams) (Country, error) {
	row := q.db.QueryRow(ctx, createCountry,
		arg.NameRo,
		arg.NameRu,
		arg.NameEn,
		arg.Iso3,
		arg.Iso2,
	)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.NameRo,
		&i.NameRu,
		&i.NameEn,
		&i.Iso3,
		&i.Iso2,
	)
	return i, err
}

const deleteAirport = `-- name: DeleteAirport :execrows
DELETE FROM airports
WHERE id = $1
`

func (q *Queries) DeleteAirport(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAirport, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCity = `-- name: DeleteCity :execrows
DELETE FROM cities
WHERE id = $1
`

func (q *Queries) DeleteCity(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCity, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCountry = `-- name: DeleteCountry :execrows
DELETE FROM countries
WHERE id = $1
`

func (q *Queries) DeleteCountry(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCountry, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAirport = `-- name: GetAirport :one
SELECT id, city_id, iata_code, icao_code, lat, lon
FROM airports
WHERE id = $1
`

func (q *Queries) GetAirport(ctx context.Context, id int64) (Airport, error) {
	row := q.db.QueryRow(ctx, getAirport, id)
	var i Airport
	err := row.Scan(
		&i.ID,
		&i.CityID,
		&i.IataCode,
		&i.IcaoCode,
		&i.Lat,
		&i.Lon,
	)
	return i, err
}

const getCitiesDropdown = `-- name: GetCitiesDropdown :many
SELECT
    c.id,
    (CASE WHEN $1::text = 'ru' THEN c.name_ru WHEN $1::text = 'ro' THEN c.name_ro ELSE c.name_en END)::text AS name,
    (CASE WHEN $1::text = 'ru' THEN co.name_ru WHEN $1::text = 'ro' THEN co.name_ro ELSE co.name_en END)::text AS country_name,
    a.iata_code AS airport_code
FROM cities c
JOIN countries co ON c.country_id = co.id
JOIN airports a ON a.city_id = c.id
WHERE
    (a.iata_code = UPPER($2::text))
    OR (($1::text = 'ru' AND (c.name_ru % $2::text OR c.name_ru ILIKE CONCAT($2::text, '%')))
        OR ($1::text = 'ro' AND (c.name_ro % $2::text OR c.name_ro ILIKE CONCAT($2::text, '%')))
        OR ($1::text = 'en' AND (c.name_en % $2::text OR c.name_en ILIKE CONCAT($2::text, '%'))))
    OR (($1::text = 'ru' AND (co.name_ru % $2::text OR co.name_ru ILIKE CONCAT($2::text, '%')))
        OR ($1::text = 'ro' AND (co.name_ro % $2::text OR co.name_ro ILIKE CONCAT($2::text, '%')))
        OR ($1::text = 'en' AND (co.name_en % $2::text OR co.name_en ILIKE CONCAT($2::text, '%'))))
ORDER BY
    (a.iata_code = UPPER($2::text)) DESC,
    GREATEST(
        similarity(CASE $1::text WHEN 'ru' THEN c.name_ru WHEN 'ro' THEN c.name_ro ELSE c.name_en END, $2::text),
        similarity(CASE $1::text WHEN 'ru' THEN co.name_ru WHEN 'ro' THEN co.name_ro ELSE co.name_en END, $2::text)
    ) DESC,
    c.population DESC NULLS LAST,
    c.is_capital DESC
LIMIT $3::bigint
`

type GetCitiesDropdownParams struct {
	Locale    string
	Search    string
	LimitRows int64
}

type GetCitiesDropdownRow struct {
	ID          int64
	Name        string
	CountryName string
	AirportCode *string
}

func (q *Queries) GetCitiesDropdown(ctx context.Context, arg GetCitiesDropdownParams) ([]GetCitiesDropdownRow, error) {
	rows, err := q.db.Query(ctx, getCitiesDropdown, arg.Locale, arg.Search, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCitiesDropdownRow
	for rows.Next() {
		var i GetCitiesDropdownRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CountryName,
			&i.AirportCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCity = `-- name: GetCity :one
SELECT id, country_id, name_ro, name_ru, name_en, is_capital, population, timezone
FROM cities
WHERE id = $1
`

func (q *Queries) GetCity(ctx context.Context, id int64) (City, error) {
	row := q.db.QueryRow(ctx, getCity, id)
	var i City
	err := row.Scan(
		&i.ID,
		&i.CountryID,
		&i.NameRo,
		&i.NameRu,
		&i.NameEn,
		&i.IsCapital,
		&i.Population,
		&i.Timezone,
	)
	return i, err
}

const getCountry = `-- name: GetCountry :one
SELECT id, name_ro, name_ru, name_en, iso3, iso2
FROM countries
WHERE id = $1
`

func (q *Queries) GetCountry(ctx context.Context, id int64) (Country, error) {
	row := q.db.QueryRow(ctx, getCountry, id)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.NameRo,
		&i.NameRu,
		&i.NameEn,
		&i.Iso3,
		&i.Iso2,
	)
	return i, err
}

const listAirports = `-- name: ListAirports :many
SELECT id, city_id, iata_code, icao_code, lat, lon
FROM airports
ORDER BY id
`

func (q *Queries) ListAirports(ctx context.Context) ([]Airport, error) {
	rows, err := q.db.Query(ctx, listAirports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Airport
	for rows.Next() {
		var i Airport
		if err := rows.Scan(
			&i.ID,
			&i.CityID,
			&i.IataCode,
			&i.IcaoCode,
			&i.Lat,
			&i.Lon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCities = `-- name: ListCities :many
SELECT id, country_id, name_ro, name_ru, name_en, is_capital, population, timezone
FROM cities
ORDER BY id
`

func (q *Queries) ListCities(ctx context.Context) ([]City, error) {
	rows, err := q.db.Query(ctx, listCities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []City
	for rows.Next() {
		var i City
		if err := rows.Scan(
			&i.ID,
			&i.CountryID,
			&i.NameRo,
			&i.NameRu,
			&i.NameEn,
			&i.IsCapital,
			&i.Population,
			&i.Timezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCountries = `-- name: ListCountries :many
SELECT id, name_ro, name_ru, name_en, iso3, iso2
FROM countries
ORDER BY id
`

func (q *Queries) ListCountries(ctx context.Context) ([]Country, error) {
	rows, err := q.db.Query(ctx, listCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Country
	for rows.Next() {
		var i Country
		if err := rows.Scan(
			&i.ID,
			&i.NameRo,
			&i.NameRu,
			&i.NameEn,
			&i.Iso3,
			&i.Iso2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAirport = `-- name: UpdateAirport :one
UPDATE airports
SET city_id = $2, iata_code = $3, icao_code = $4, lat = $5, lon = $6
WHERE id = $1
RETURNING id, city_id, iata_code, icao_code, lat, lon
`

type UpdateAirportParams struct {
	ID       int64
	CityID   int64
	IataCode *string
	IcaoCode *string
	Lat      *float64
	Lon      *float64
}

func (q *Queries) UpdateAirport(ctx context.Context, arg UpdateAirportParams) (Airport, error) {
	row := q.db.QueryRow(ctx, updateAirport,
		arg.ID,
		arg.CityID,
		arg.IataCode,
		arg.IcaoCode,
		arg.Lat,
		arg.Lon,
	)
	var i Airport
	err := row.Scan(
		&i.ID,
		&i.CityID,
		&i.IataCode,
		&i.IcaoCode,
		&i.Lat,
		&i.Lon,
	)
	return i, err
}

const updateCity = `-- name: UpdateCity :one
UPDATE cities
SET country_id = $2, name_ro = $3, name_ru = $4, name_en = $5, is_capital = $6, population = $7, timezone = $8
WHERE id = $1
RETURNING id, country_id, name_ro, name_ru, name_en, is_capital, population, timezone
`

type UpdateCityParams struct {
	ID         int64
	CountryID  int64
	NameRo     string
	NameRu     string
	NameEn     string
	IsCapital  bool
	Population *int64
	Timezone   *string
}

func (q *Queries) UpdateCity(ctx context.Context, arg UpdateCityParams) (City, error) {
	row := q.db.QueryRow(ctx, updateCity,
		arg.ID,
		arg.CountryID,
		arg.NameRo,
		arg.NameRu,
		arg.NameEn,
		arg.IsCapital,
		arg.Population,
		arg.Timezone,
	)
	var i City
	err := row.Scan(
		&i.ID,
		&i.CountryID,
		&i.NameRo,
		&i.NameRu,
		&i.NameEn,
		&i.IsCapital,
		&i.Population,
		&i.Timezone,
	)
	return i, err
}

const updateCountry = `-- name: UpdateCountry :one
UPDATE countries
SET name_ro = $2, name_ru = $3, name_en = $4, iso3 = $5, iso2 = $6
WHERE id = $1
RETURNING id, name_ro, name_ru, name_en, iso3, iso2
`

type UpdateCountryParams struct {
	ID     int64
	NameRo string
	NameRu string
	NameEn string
	Iso3   string
	Iso2   string
}

func (q *Queries) UpdateCountry(ctx context.Context, arg UpdateCountryParams) (Country, error) {
	row := q.db.QueryRow(ctx, updateCountry,
		arg.ID,
		arg.NameRo,
		arg.NameRu,
		arg.NameEn,
		arg.Iso3,
		arg.Iso2,
	)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.NameRo,
		&i.NameRu,
		&i.NameEn,
		&i.Iso3,
		&i.Iso2,
	)
	return i, err
}
