// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Airport struct {
	ID       int64
	CityID   int64
	IataCode *string
	IcaoCode *string
	Lat      *float64
	Lon      *float64
}

type City struct {
	ID         int64
	CountryID  int64
	NameRo     string
	NameRu     string
	NameEn     string
	IsCapital  bool
	Population *int64
	Timezone   *string
}

type Country struct {
	ID     int64
	NameRo string
	NameRu string
	NameEn string
	Iso3   string
	Iso2   string
}
